name: Main

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

  # integration:
  #   name: Integration Tests
    #   needs: test
  #   runs-on: ubuntu-latest

  # release: